name: Node.js CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      #- run: npm clean install
      #- run: npm run build --if-present
      - name: build Dockerfile
        run: docker build -t ahmedsherifmo/node-server .
      - name: test vars
        run: echo $DOCKER_PASSWORD
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ahmedsherifmo
          password: dckr_pat_ojL53sqkpTJYpwcx9e3s8C05SKk
      - name: Push-image-to-reg
        run: docker push ahmedsherifmo/node-server  
  test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Test stage
        run: npm test
